#!/usr/bin/env bash
# Configure domain zone

get_ip () {
    dig $1 | grep -A1 'ANSWER SECTION:' | awk 'NR>1'
}

show_subdomain () {
    echo 'The subdomain' $1 'is a' $2 'record and points to' $3
}

print_output () {
    output=$( get_ip "$1.$2" )
    record_type=$( echo "$output" | awk '{print $4}' )
    destination=$(echo "$output" | awk '{print $5}')
    show_subdomain $1 $record_type $destination
}

if [ $# -eq 0 ];
then
    exit 1
fi
if [ $# -eq 1 ];
then
    for subdomain in 'www' 'lb-01' 'web-01' 'web-02';
    do
        print_output $subdomain $1
    done
fi

if [ $# -eq 2 ];
then
    print_output $2 $1
fi
