#!/usr/bin/env bash
# Install and configures a new Ubuntu machine

sudo apt-get update

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx restart
