#!/usr/bin/env bash
# Install and configures a new Ubuntu machine

sudo apt-get update

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/" /etc/nginx/sites-available/default

sudo sed -i "s/listen 80 default_server;/listen 80 default_server;\n\n\terror_page 404 \/404.html;\n\tlocation \/404.html {\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

# shellcheck disable=SC2154
sudo sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;\n\n\tadd_header X-Served-By '$(hostname)';/" /etc/nginx/sites-available/default

sudo service nginx restart
