#!/usr/bin/env bash
# Script that installs and configures HAproxy in a load balancer 

sudo apt-get -y update
sudo apt-get -y install haproxy

echo -e "\nfrontend web-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tmode http\n\tbalance roundrobin\n\tserver 105584-web-01 54.160.69.142:80 check\n\tserver 105584-web-02 54.236.205.211:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

