#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.

mysqldump -u root -p"$1" --all-databases --master-data > backup.sql

created_at=$(date +%d-%m-%Y)

archive_name="$created_at".tar.gz

tar -czf "$archive_name" backup.sql
